name: peer_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # Correct indentation for http
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.4+3  # Make sure image_picker is added
  flutter_secure_storage: ^9.2.2
  graphql_flutter: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/PeerLogo_Color_RGB.png
    - assets/PeerSignet_Color_RGB.png
